//! `cfg_defines.h` -> `tt_isa::cfg::generated`.

use std::collections::BTreeMap;

use crate::fetch::fetch_cfg_defines;
use crate::pin;
use crate::util::{rustfmt, sha256, workspace_root};

/// Regenerate `tt-isa`'s backend-configuration field table.
///
/// `cfg_defines.h` holds 827 fields across seven sections. The plan's rule is
/// "generate, never transcribe", and this is that generator.
///
/// The output is **committed** rather than produced by a build script. That keeps
/// `tt-isa` free of build dependencies and buildable for `riscv32im` with nothing
/// but rustc, makes the table reviewable, and turns a pin bump into a diff someone
/// can read. `--check` regenerates into memory and compares, so CI can prove the
/// committed file matches the pinned header.
pub fn gen_cfg(check_only: bool) -> Result<(), String> {
    let root = workspace_root();
    let header = root.join("vendor").join("cfg_defines.h");
    if !header.exists() {
        fetch_cfg_defines(&header)?;
    }
    let got = sha256(&header)?;
    if got != pin::CFG_DEFINES_SHA256 {
        return Err(format!(
            "{} hashes {got}, not the pinned {}.\n\
             Delete it to re-fetch, or update PINS.toml and xtask's pin module if \
             the bump is intentional.",
            header.display(),
            pin::CFG_DEFINES_SHA256
        ));
    }

    let source = std::fs::read_to_string(&header)
        .map_err(|e| format!("reading {}: {e}", header.display()))?;
    let rendered = render_cfg(&parse_cfg_defines(&source)?)?;

    let dest = root.join("crates/tt-isa/src/cfg/generated.rs");

    // Format the output rather than trying to emit rustfmt-clean code by hand.
    // Long field names push some lines past the width limit, and guessing where
    // rustfmt would wrap them is a losing game -- it also makes `--check` compare
    // two things produced the same way, so it cannot fail for cosmetic reasons.
    let generated = rustfmt(&rendered, &root)?;

    if check_only {
        let current = std::fs::read_to_string(&dest)
            .map_err(|e| format!("reading {}: {e}", dest.display()))?;
        if current == generated {
            println!(
                "ok: {} is up to date with the pinned header",
                dest.display()
            );
            Ok(())
        } else {
            Err(format!(
                "{} is out of date with the pinned cfg_defines.h.\n\
                 Run `cargo xtask gen-cfg` and commit the result.",
                dest.display()
            ))
        }
    } else {
        std::fs::write(&dest, &generated)
            .map_err(|e| format!("writing {}: {e}", dest.display()))?;
        println!("wrote {} ({} bytes)", dest.display(), generated.len());
        Ok(())
    }
}

/// One parsed field.
struct Field {
    name: String,
    section: String,
    addr32: u32,
    shamt: u32,
    /// Hex digits of the mask, unparsed — two fields have 128-bit masks.
    mask: String,
}

/// Parse `#define NAME_{ADDR32,SHAMT,MASK} VALUE`, tracking the current section.
///
/// The file is machine-generated by Tenstorrent's `genCfgRegs.py`, so the format
/// is regular: every field has exactly those three defines plus an `_RMW`
/// convenience macro, which is skipped because it carries no information the
/// other three do not.
///
/// # Why this is hand-rolled rather than bindgen
///
/// bindgen runs on this header and produces 2467 flat `u32` constants, but two
/// things make it the wrong tool:
///
/// * **It silently drops the `TileDescriptor` masks.** They are
///   `0xffffffffffffffffffffffffffffffff`, which clang rejects as "integer
///   literal is too large to be represented in any integer type". bindgen emits
///   the field's `ADDR32` and `SHAMT` and omits the `MASK`, with no diagnostic —
///   a field that looks complete and is not. The loop below errors on exactly
///   that shape instead, which is how the `_CFGREG_BASE` defines were found.
/// * **It discards the section comments**, and section membership is the whole
///   point: it decides `Config` versus `ThreadConfig`, and therefore which write
///   instruction is legal, whether RISC-V may write the field at all, and whether
///   values are 16 or 32 bits wide. Without it there is no typing to do.
///
/// The resilience a real C parser would buy is bought here instead by failing
/// loudly: a missing triple, a field before any section header, a section with no
/// base, an unexpected wide mask, or zero fields parsed are all hard errors, and
/// `gen-cfg --check` runs in CI and pre-commit so a pin bump cannot drift quietly.
///
/// bindgen *is* the right tool for `tt-kmd`'s `ioctl.h`, which is real C with
/// structs rather than a wall of macros.
/// A field under construction: its section, then `ADDR32`, `SHAMT` and `MASK` as
/// each is encountered. The header emits them on consecutive lines, but nothing
/// in the format guarantees that, so they are collected independently.
type PartialField = (String, Option<u32>, Option<u32>, Option<String>);

fn parse_cfg_defines(source: &str) -> Result<CfgTable, String> {
    let mut section = String::new();
    let mut parts: BTreeMap<String, PartialField> = BTreeMap::new();
    let mut cfg_state_size = None;
    let mut thd_state_size = None;
    let mut section_bases: BTreeMap<String, u32> = BTreeMap::new();

    for line in source.lines() {
        if let Some(rest) = line.strip_prefix("// Registers for ") {
            section = rest.trim().to_string();
            continue;
        }
        let Some(rest) = line.strip_prefix("#define ") else {
            continue;
        };
        let mut it = rest.split_whitespace();
        let (Some(name), Some(value)) = (it.next(), it.next()) else {
            continue;
        };

        match name {
            "CFG_STATE_SIZE" => {
                cfg_state_size = parse_int(value);
                continue;
            }
            "THD_STATE_SIZE" => {
                thd_state_size = parse_int(value);
                continue;
            }
            _ => {}
        }

        // `_RMW` expands to the other three; nothing to learn from it.
        let Some((stem, kind)) = name.rsplit_once('_') else {
            continue;
        };
        if !matches!(kind, "ADDR32" | "SHAMT" | "MASK") {
            continue;
        }
        // `<SECTION>_CFGREG_BASE_ADDR32` is the first word index of a section,
        // not a field: it has no SHAMT or MASK. There is exactly one per section,
        // and together they partition the Config space.
        if let Some(sec) = stem.strip_suffix("_CFGREG_BASE") {
            if kind == "ADDR32" {
                if let Some(v) = parse_int(value) {
                    section_bases.insert(sec.to_string(), v);
                }
            }
            continue;
        }
        let entry = parts
            .entry(stem.to_string())
            .or_insert_with(|| (section.clone(), None, None, None));
        match kind {
            "ADDR32" => entry.1 = parse_int(value),
            "SHAMT" => entry.2 = parse_int(value),
            "MASK" => entry.3 = Some(value.to_string()),
            _ => unreachable!(),
        }
    }

    let cfg_state_size = cfg_state_size.ok_or("CFG_STATE_SIZE not found")?;
    let thd_state_size = thd_state_size.ok_or("THD_STATE_SIZE not found")?;

    let mut fields = Vec::new();
    for (name, (section, addr32, shamt, mask)) in parts {
        let (Some(addr32), Some(shamt), Some(mask)) = (addr32, shamt, mask) else {
            return Err(format!(
                "field `{name}` is missing one of ADDR32/SHAMT/MASK"
            ));
        };
        if section.is_empty() {
            return Err(format!("field `{name}` appears before any section header"));
        }
        fields.push(Field {
            name,
            section,
            addr32,
            shamt,
            mask,
        });
    }
    if fields.is_empty() {
        return Err("parsed no fields; has the header format changed?".into());
    }
    for f in &fields {
        if !section_bases.contains_key(&f.section) {
            return Err(format!(
                "section `{}` has no _CFGREG_BASE_ADDR32",
                f.section
            ));
        }
    }
    Ok(CfgTable {
        fields,
        cfg_state_size,
        thd_state_size,
        section_bases,
    })
}

struct CfgTable {
    fields: Vec<Field>,
    cfg_state_size: u32,
    thd_state_size: u32,
    /// First `Config` word index of each section, from `<SECTION>_CFGREG_BASE_ADDR32`.
    section_bases: BTreeMap<String, u32>,
}

fn parse_int(s: &str) -> Option<u32> {
    let s = s.trim();
    match s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
        Some(hex) => u32::from_str_radix(hex, 16).ok(),
        None => s.parse().ok(),
    }
}

/// Emit the Rust module.
fn render_cfg(table: &CfgTable) -> Result<String, String> {
    use std::fmt::Write;

    // Section name -> (module name, is ThreadConfig).
    let module_of =
        |section: &str| -> (String, bool) { (section.to_ascii_lowercase(), section == "THREAD") };

    let mut by_module: BTreeMap<String, Vec<&Field>> = BTreeMap::new();
    for f in &table.fields {
        by_module
            .entry(module_of(&f.section).0)
            .or_default()
            .push(f);
    }

    let mut out = String::new();
    writeln!(
        out,
        "//! Tensix backend-configuration fields, generated from `cfg_defines.h`.\n\
         //!\n\
         //! **Do not edit.** Regenerate with `cargo xtask gen-cfg`; CI checks that this\n\
         //! file matches the header pinned in `PINS.toml`.\n\
         //!\n\
         //! Source: tt-metal `{}`, `tt_metal/hw/inc/blackhole/cfg_defines.h`\n\
         //! ({} fields across {} sections).\n\
         //!\n\
         //! Field names are kept exactly as `cfg_defines.h` spells them, so that a\n\
         //! name in the specification can be searched for here without translation.\n\
         //! That is why this module allows non-upper-case globals.\n\
         #![allow(non_upper_case_globals)]\n\
         #![allow(clippy::unreadable_literal)]\n",
        pin::TT_METAL_REV,
        table.fields.len(),
        by_module.len(),
    )
    .unwrap();

    writeln!(
        out,
        "use super::{{ConfigField, ConfigSpan, ThreadConfigField}};\n"
    )
    .unwrap();
    writeln!(
        out,
        "/// `uint32_t Config[2][CFG_STATE_SIZE * 4]` — the multiplier is in the\n\
         /// declaration, so one bank holds `CFG_STATE_SIZE * 4` words.\n\
         pub const CFG_STATE_SIZE: u32 = {};\n",
        table.cfg_state_size
    )
    .unwrap();
    writeln!(
        out,
        "/// `struct {{uint16_t Value, Padding;}} ThreadConfig[3][THD_STATE_SIZE]`.\n\
         pub const THD_STATE_SIZE: u32 = {};\n",
        table.thd_state_size
    )
    .unwrap();

    let mut all_config = Vec::new();
    let mut all_thread = Vec::new();
    let mut all_spans = Vec::new();
    let mut per_section: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();

    for (module, fields) in &by_module {
        let is_thread = fields[0].section == "THREAD";
        let section = &fields[0].section;
        writeln!(
            out,
            "/// `// Registers for {section}` — {} fields, indexing {}.",
            fields.len(),
            if is_thread {
                "`ThreadConfig` (write with `SETC16`)"
            } else {
                "`Config` (write with `WRCFG`)"
            }
        )
        .unwrap();
        writeln!(out, "pub mod {module} {{").unwrap();
        writeln!(out, "    use super::*;\n").unwrap();
        let base = table.section_bases[section];
        writeln!(
            out,
            "    /// First word index of this section, from `{section}_CFGREG_BASE_ADDR32`.\n    \
             pub const CFGREG_BASE: u16 = {base};\n"
        )
        .unwrap();

        for f in fields {
            let addr32 = f.addr32;
            let shamt = f.shamt;
            let hex = f.mask.trim_start_matches("0x").trim_start_matches("0X");
            let wide = hex.len() > 8;

            if wide {
                // A whole-register aggregate rather than a bitfield: mask is all
                // ones and the shift is zero. Anything else would be a parse bug.
                if shamt != 0 || hex.chars().any(|c| c != 'f' && c != 'F') {
                    return Err(format!(
                        "{}: mask {} is wider than 32 bits but is not a whole-word run",
                        f.name, f.mask
                    ));
                }
                let words = (hex.len() / 8) as u32;
                writeln!(
                    out,
                    "    /// `Config[{addr32}..{}]` — a {}-bit aggregate, not a bitfield.",
                    addr32 + words,
                    words * 32
                )
                .unwrap();
                writeln!(
                    out,
                    "    pub const {}: ConfigSpan = ConfigSpan::new({addr32}, {words});",
                    f.name
                )
                .unwrap();
                all_spans.push((module.clone(), f.name.clone()));
            } else if is_thread {
                writeln!(
                    out,
                    "    pub const {}: ThreadConfigField = ThreadConfigField::new({addr32}, {shamt}, 0x{hex});",
                    f.name
                )
                .unwrap();
                all_thread.push((module.clone(), f.name.clone()));
            } else {
                writeln!(
                    out,
                    "    pub const {}: ConfigField = ConfigField::new({addr32}, {shamt}, 0x{hex});",
                    f.name
                )
                .unwrap();
                all_config.push((module.clone(), f.name.clone()));
                per_section
                    .entry(module.clone())
                    .or_default()
                    .push((module.clone(), f.name.clone()));
            }
        }
        writeln!(out, "}}\n").unwrap();
    }

    // Flat tables, so invariants can be asserted over every field at once rather
    // than a sample. This is what catches a misclassified section.
    let emit_table =
        |out: &mut String, name: &str, ty: &str, items: &[(String, String)], doc: &str| {
            writeln!(out, "/// {doc}").unwrap();
            writeln!(out, "pub static {name}: &[(&str, {ty})] = &[").unwrap();
            for (module, field) in items {
                writeln!(out, "    (\"{field}\", {module}::{field}),").unwrap();
            }
            writeln!(out, "];\n").unwrap();
        };
    emit_table(
        &mut out,
        "ALL_CONFIG_FIELDS",
        "ConfigField",
        &all_config,
        "Every `Config` bitfield, for table-wide invariant checks.",
    );
    emit_table(
        &mut out,
        "ALL_THREAD_CONFIG_FIELDS",
        "ThreadConfigField",
        &all_thread,
        "Every `ThreadConfig` bitfield, for table-wide invariant checks.",
    );
    emit_table(
        &mut out,
        "ALL_CONFIG_SPANS",
        "ConfigSpan",
        &all_spans,
        "Every multi-word `Config` aggregate.",
    );

    // Per-section tables, so the section-partitioning invariant can be checked.
    // A field attributed to the wrong section is still in bounds for `Config` as
    // a whole, so only a per-section check catches it.
    for (module, items) in &per_section {
        emit_table(
            &mut out,
            &format!("{}_FIELDS", module.to_ascii_uppercase()),
            "ConfigField",
            items,
            &format!("Every `Config` bitfield in the `{module}` section."),
        );
    }

    Ok(out)
}
